version: "3.9"

services:

  eureka-server:
    build: ./services/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  config-server:
    build: ./services/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - microservices-network

  gateway:
    build: ./services/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - microservices-network

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge