server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: incident-service
          uri: lb://incident-service
          predicates:
            - Path=/incidents/**

  security:
    oauth2:
      resourceserver:
        jwt:
          # On met une adresse bidon juste pour voir si ça démarre
          issuer-uri: http://localhost:8180/realms/SGI-realm
          jwk-set-uri: http://localhost:8180/realms/SGI-realm/protocol/openid-connect/certs

# On désactive le contact avec Eureka temporairement pour isoler le problème
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false